######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
     post: '[btn.blog](/)'
     wiki: '[btn.wiki](/wiki/)'
     friends: '[友链](/friends/)'
     about: '[关于](/about/)'
  # Sidebar widgets
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss:  /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: 欢迎
      content: | # support markdown
          <span id="jinrishici-sentence">夏日当空，心如深渊</span><script src="https://sdk.jinrishici.com/v2/browser/jinrishici.js" charset="utf-8"></script>

######## Main ########
breadcrumb:
  home: home # config.title / config.author / home or custom content

######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 150
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share: [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 5

######## Comments ########
comments:
  service: artalk
  # Artalk
  # https://artalk.js.org/
  artalk:
    css: https://unpkg.com/artalk@2.5.5/dist/Artalk.css
    js: https://unpkg.com/artalk@2.5.5/dist/Artalk.js 
    server: https://artalk.hzchu.top # 后端服务地址
    placeholder: '此时无声胜有声'
    site: Blog
    emoticons: https://raw.hzchu.top/thun888/asstes/master/files/json/artalk/default.json
    darkMode: auto

######## Footer ########
footer:
  social:
     - title: RSS
     - icon: '<img src="/img/icons/25678f144c438.svg"/>'
       url: /atom.xml
     - icon: '<img src="/img/icons/08a41b181ce68.svg"/>'
       url: https://github.com/thun888
     - icon: '<img src="/img/icons/a1b00e20f425d.svg"/>'
       url: mailto:thun888@qq.com
     - icon: '<img src="/img/icons/20210610162918.svg"/>'
       url: https://share.hzchu.top
  sitemap:
     '博客':
       - '[大事记](/big/)'
       - '[随记](https://notes.hzchu.top/)'
      # - '[后台](https://hexo.orzz.ml/hpp/admin/dash/home/)'
       - '[归档](/archives/)'
     '项目':
       - '[杂物](/wiki/杂物间/)'
       - '[峰间云海](/wiki/fcloud/)'
     '社交':
       - '[友链](/friends/)'
       - '[留言板](/say/)'
       - '[BiliBili](https://space.bilibili.com/451090261)'
       - '[邮箱](mailto:thun888@qq.com)'
     '更多':
       - '[关于本站](/about/)'
       - '[云盘](https://pan.hzchu.top)'
  content: | # 支持 Markdown 格式
    本站由 [@thun888](/about/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    <script>!function(p){"use strict";!function(t){var s=window,e=document,i=p,c="".concat("https:"===e.location.protocol?"https://":"http://","sdk.51.la/js-sdk-pro.min.js"),n=e.createElement("script"),r=e.getElementsByTagName("script")[0];n.type="text/javascript",n.setAttribute("charset","UTF-8"),n.async=!0,n.src=c,n.id="LA_COLLECT",i.d=n;var o=function(){s.LA.ids.push(i)};s.LA?s.LA.ids&&o():(s.LA=p,s.LA.ids=[],o()),r.parentNode.insertBefore(n,r)}()}({id:"JnLm5m7MJcDkpWaM",ck:"JnLm5m7MJcDkpWaM"});</script>
######## Tag Plugins ########
tag_plugins:
  image:
    fancybox: true

style:
  darkmode: auto # auto / always / false
  theme:
    light: '#f8f8f8'
    dark: '#313438'
  animated_avatar:
    animate: auto # auto, always
    background: /img/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px
  gradient: # https://webgradients.com/
    start: 'linear-gradient(to right, #92fe9d 0%, #00c9ff 50%, #92fe9d 100%)'
    search: 'linear-gradient(to right, #e0e0e0,#e0e0e0)'

default:
  avatar: /img/svg/3442075.svg
  link: /img/svg/8f277b4ee0ecd.svg
  cover: /img/svg/76b86c0226ffd.svg
  image: /img/svg/2659360.svg

sitemap:
  path: sitemap.xml