######## Sidebar ########
sidebar:
  logo:
    avatar: '[config.avatar](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
     post: '[btn.blog](/)'
     wiki: '[btn.wiki](/wiki/)'
     friends: '[友链](/friends/)'
     about: '[关于](/about/)'
  # Sidebar widgets
  widget_layout:
    index: [welcome, recent] # for home/wiki/categories/tags/archives/404 pages
    page: [welcome, toc] # for pages using 'layout:page'
    post: [toc, repo_info] # for pages using 'layout:post'
    wiki: [toc, repo_info, wiki_more] # for pages using 'layout:wiki'
  widgets:
    # Recent update
    recent:
      layout: recent
      rss:  /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5
      fallback: recent # Use a backup widget when toc does not exist.
    # welcome
    welcome:
      layout: markdown
      title: 欢迎
      content: | # support markdown
          <span id="jinrishici-sentence">夏日当空，心如深渊</span><script src="https://sdk.jinrishici.com/v2/browser/jinrishici.js" charset="utf-8"></script>


######## Article ########
article:
  # 如果没有指定封面，是否根据 tags 作为关键词搜索封面？
  auto_cover: false # search from https://source.unsplash.com/
  # 如果没有指定 excerpt 和 description，将自动取多长的内容作为文章摘要？
  auto_excerpt: 150
  # 分类颜色
  category_color:
    '新闻稿': '#DA0F47'
  # 文章许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享
  share: [wechat, weibo, email, link]
  # 相关文章，需要安装插件 (for layout: post)
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    max_count: 5

######## Comments ########
comments:
  service: artalk
  # Artalk
  # https://artalk.js.org/
  artalk:
    css: https://unpkg.com/artalk@2.5.5/dist/Artalk.css
    js: https://unpkg.com/artalk@2.5.5/dist/Artalk.js 
    server: https://artalk.hzchu.top # 后端服务地址
    placeholder: '此时无声胜有声'
    site: Blog
    emoticons: https://raw.hzchu.top/thun888/asstes/master/files/json/artalk/default.json
    darkMode: auto

######## Footer ########
footer:
  social:
     - title: RSS
     - icon: '<img src="/img/icons/25678f144c438.svg"/>'
       url: /atom.xml
     - icon: '<img src="/img/icons/08a41b181ce68.svg"/>'
       url: https://github.com/thun888
     - icon: '<img src="/img/icons/a1b00e20f425d.svg"/>'
       url: mailto:thun888@qq.com
     - icon: '<img src="/img/icons/20210610162918.svg"/>'
       url: https://share.hzchu.top
  sitemap:
     '博客':
       - '[大事记](/big/)'
       - '[随记](https://notes.hzchu.top/)'
      # - '[后台](https://hexo.orzz.ml/hpp/admin/dash/home/)'
       - '[归档](/archives/)'
     '项目':
       - '[杂物](/wiki/杂物间/)'
       - '[峰间云海](/wiki/fcloud/)'
     '社交':
       - '[友链](/friends/)'
       - '[留言板](/say/)'
       - '[BiliBili](https://space.bilibili.com/451090261)'
       - '[邮箱](mailto:thun888@qq.com)'
     '更多':
       - '[关于本站](/about/)'
       - '[云盘](https://pan.hzchu.top)'
  content: | # 支持 Markdown 格式
    本站由 [@thun888](/about/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
    <script>!function(p){"use strict";!function(t){var s=window,e=document,i=p,c="".concat("https:"===e.location.protocol?"https://":"http://","sdk.51.la/js-sdk-pro.min.js"),n=e.createElement("script"),r=e.getElementsByTagName("script")[0];n.type="text/javascript",n.setAttribute("charset","UTF-8"),n.async=!0,n.src=c,n.id="LA_COLLECT",i.d=n;var o=function(){s.LA.ids.push(i)};s.LA?s.LA.ids&&o():(s.LA=p,s.LA.ids=[],o()),r.parentNode.insertBefore(n,r)}()}({id:"JnLm5m7MJcDkpWaM",ck:"JnLm5m7MJcDkpWaM"});</script>
    <script id="LA-DATA-WIDGET" crossorigin="anonymous" charset="UTF-8" src="https://v6-widget.51.la/v6/JnLm5m7MJcDkpWaM/quote.js?theme=0&f=12&display=0,0,0,1,0,1,0,1"></script>
######## Tag Plugins ########
tag_plugins:
  image:
    fancybox: true # true, false
    parse_markdown: true # 把 markdown 格式的图片解析成图片标签
  mermaid:
    enable: true
    # Available themes: default | dark | forest | neutral
    # 推荐使用 dark 主题 在夜间模式下显示效果更好
    theme: default

  # 代码块复制按钮
  copycode:
    enable: true
    js: /js/plugins/copycode.js
    default_text: 'Copy'
    success_text: 'Copied'
######## JS Plugins ########
plugins:
  ## optional plugins ##
  fancybox:
    enable: true
    js: https://jsd.hzchu.top/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    css: https://jsd.hzchu.top/npm/@fancyapps/ui@4.0/dist/fancybox.css
    # 可以处理评论区的图片（不支持 iframe 类评论系统）例如：
    # 使用twikoo评论可以写: .tk-content img:not([class*="emo"])
    # 使用waline评论可以写: #waline_container .vcontent img
    selector: .md-text img # 多个选择器用英文逗号隔开

style:
  font-family:
    logo: '"LXGW WenKai Screen",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen",system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
default:
  avatar: /img/svg/3442075.svg
  link: /img/svg/8f277b4ee0ecd.svg
  cover: /img/svg/76b86c0226ffd.svg
  image: /img/svg/2659360.svg


api_host:
  ghapi: https://cfproxy.hzchu.top/https://api.github.com
  ghraw: https://raw.hzchu.top
  gist: https://cfproxy.hzchu.top/https://gist.github.com


sitemap:
  path: sitemap.xml

mermaid:
  enable: true
  # js: https://unpkg.com/mermaid@9.0.0/dist/mermaid.min.js
  js: https://jsd.hzchu.top/npm/mermaid@v9/dist/mermaid.min.js
  # Available themes: default | dark | forest | neutral
  theme: neutral
