name: 自动部署
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Hexo
        run: |
          export TZ='Asia/Shanghai'

          npm install hexo-cli -g npm-check-updates
          ncu
      - name: Cache Modules
        uses: actions/cache@v1
        id: cache-modules
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Generate
        run: |
          hexo clean
          hexo g
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: gh-page
          publish_dir: ./public
      - name: Tgbot
        run: >
          curl -d 'chat_id=1183316935' -d 'text=博客部署完成' -X POST ${{ secrets.POST
          }}
