name: status
on: 
  schedule:
    - cron: '0/5 * * * *'
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        export TZ='Asia/Shanghai'
        git clone -b gh-page https://github.com/thun888/myblog.git
        rm -rf ./myblog/.git/ 
        mv ./myblog/index.html ./lab/`date +%Y_%m_%d_%H:%M:%S`.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_branch: status-page
        publish_dir: ./myblog
